# Generated by Django 2.1.7 on 2019-02-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info_app', '0002_auto_20190220_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='cloud_stat',
            new_name='cloud_desc',
        ),
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
