# Generated by Django 2.1.7 on 2019-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info_app', '0003_auto_20190220_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='region_id',
            field=models.CharField(max_length=50),
        ),
    ]
