# Generated by Django 2.1.7 on 2019-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info_app', '0004_auto_20190220_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
