# Generated by Django 2.1.7 on 2019-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info_app', '0006_auto_20190220_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
