# Generated by Django 2.1.7 on 2019-02-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info_app', '0007_auto_20190220_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.CharField(max_length=50),
        ),
    ]
