# Generated by Django 2.1.7 on 2019-02-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info_app', '0008_auto_20190220_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'get_latest_by': 'datetime'},
        ),
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
